# 树回归

### CART算法的代码实现

In [1]:
import numpy as np

In [2]:
def loadDataSet(fileName):
    dataMat = []
    fr = open(fileName)
    for line in fr.readlines():
        curline = line.strip().split('\t')
        flatLine = map(float, curline)
        dataMat.append(flatLine)
    return dataMat

In [38]:
def binSplitDataSet(dataSet, feature, value):
    mat0 = dataSet[np.nonzero(dataSet[:, feature] > value)[0], : ]
    mat1 = dataSet[np.nonzero(dataSet[:, feature] <= value)[0], : ]
    return mat0, mat1

In [16]:
testMat = np.matrix(np.eye(4))

In [18]:
testMat

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [39]:
mat0, mat1 = binSplitDataSet(testMat, 1, 0.5)

In [40]:
mat0

matrix([[0., 1., 0., 0.]])

In [41]:
mat1

matrix([[1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [29]:
testMat[:, 1] > 0.5

matrix([[False],
        [ True],
        [False],
        [False]])

In [31]:
a = np.nonzero(testMat[:, 1] > 0.5)

In [32]:
type(a)

tuple

In [36]:
a

(array([1], dtype=int64), array([0], dtype=int64))

In [42]:
np.nonzero?

In [44]:
def regLeaf(dataSet):
    return mean(dataSet[:, -1])

In [47]:
def regErr(dataSet):
    return var(dataSet[:, -1]) * shape(dataSet)[0]

In [46]:
def createTree(dataSet, leafType=regLeaf, errType=regErr, ops=(1,4)):
    feat, val = chooseBestSplit(dataSet, leafType, errType, ops)
    if feat == None: return val
    retTree = {}
    retTree['spInd'] = feat
    retTree['spVal'] = val
    lSet, rSet = binSplitDataSet(dataSet, feat, val)
    retTree['left'] = createTree(lSet, leafType, errType, ops)
    retTree['right'] = createTree(rSet, leafType, errType, ops)
    return retTree

In [48]:
for i in range(5):
    print(i)

0
1
2
3
4
